// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPx2BNoV9C0otxN6wGL7aclbWglmNggNU',
    appId: '1:955783594656:web:61608a61c9e077cf6cbfc5',
    messagingSenderId: '955783594656',
    projectId: 'chat-app-1b8e5',
    authDomain: 'chat-app-1b8e5.firebaseapp.com',
    storageBucket: 'chat-app-1b8e5.appspot.com',
    measurementId: 'G-PFYZHJG1NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArHbdnYyhEOtp--431g5PDvgAIEjEdZqg',
    appId: '1:955783594656:android:5cc495a606cfb7006cbfc5',
    messagingSenderId: '955783594656',
    projectId: 'chat-app-1b8e5',
    storageBucket: 'chat-app-1b8e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN-UTCYHR3bZOKjxw_ZKuRq4ccH4n8aHE',
    appId: '1:955783594656:ios:da9d685f3f68c4666cbfc5',
    messagingSenderId: '955783594656',
    projectId: 'chat-app-1b8e5',
    storageBucket: 'chat-app-1b8e5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN-UTCYHR3bZOKjxw_ZKuRq4ccH4n8aHE',
    appId: '1:955783594656:ios:4ad25bdd70cf5db86cbfc5',
    messagingSenderId: '955783594656',
    projectId: 'chat-app-1b8e5',
    storageBucket: 'chat-app-1b8e5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
